### ISSUE TITLE
There was an error.

### ISSUE THREAD

**Issue by xuxucca** [shadowcz007/comfyui-sound-lab#2]
got prompt
H:\Anaconda3\envs\compy311\Lib\site-packages\torch\nn\utils\weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
H:\Anaconda3\envs\compy311\Lib\site-packages\transformers\models\encodec\modeling_encodec.py:120: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.register_buffer("padding_total", torch.tensor(kernel_size - stride, dtype=torch.int64), persistent=False)
H:\Anaconda3\envs\compy311\Lib\site-packages\transformers\models\musicgen\modeling_musicgen.py:623: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(
!!! Exception during processing!!! probability tensor contains either `inf`, `nan` or element < 0
Traceback (most recent call last):
  File "H:\com\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\com\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\com\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\com\ComfyUI\custom_nodes\comfyui-sound-lab\nodes\musicNode.py", line 148, in run
    audio_values = self.audio_model.generate(**inputs.to(device),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Anaconda3\envs\compy311\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "H:\Anaconda3\envs\compy311\Lib\site-packages\transformers\models\musicgen\modeling_musicgen.py", line 2858, in generate
    outputs = self._sample(
              ^^^^^^^^^^^^^
  File "H:\Anaconda3\envs\compy311\Lib\site-packages\transformers\generation\utils.py", line 2437, in _sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by GeekerWu** [comment]
torch2.3+cuda121 flash_atten 自己选了一个 2.3的版本 用cpu 跑musicgen 10s长度 能跑出来，换成auto模式和你报一样的错。。 之后audio lab 选什么都会 报 python311.dll unknowfile的错。放弃了就。 这个错我看LLM的也会报这个错，do_sample的时候会报。估计得改项目代码了。 可能我的是RTX2080 flash attention 目前不支持audio lab 报 FlashAttention only supports Ampere GPUs or newer.
