### ISSUE TITLE
一装上就报错，请问什么问题

### ISSUE THREAD

**Issue by liaceboy** [shadowcz007/comfyui-sound-lab#9]
ERROR: Exception:
Traceback (most recent call last):
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3070, in _dep_map
    return self.__dep_map
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2863, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\pip\_vendor\packaging\requirements.py", line 36, in __init__
    parsed = _parse_requirement(requirement_string)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\pip\_vendor\packaging\_parser.py", line 62, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\pip\_vendor\packaging\_parser.py", line 80, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\pip\_vendor\packaging\_parser.py", line 118, in _parse_requirement_details
    specifier = _parse_specifier(tokenizer)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\pip\_vendor\packaging\_parser.py", line 214, in _parse_specifier
    parsed_specifiers = _parse_version_many(tokenizer)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\pip\_vendor\packaging\_parser.py", line 229, in _parse_version_many
    tokenizer.raise_syntax_error(
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\pip\_vendor\packaging\_tokenizer.py", line 167, in raise_syntax_error
    raise ParserSyntaxError(
pip._vendor.packaging._tokenizer.ParserSyntaxError: .* suffix can only be used with `==` or `!=` operators
    numpy (>=1.19.*) ; python_version >= "3.7"
           ~~~~~~~^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\pip\_internal\cli\base_command.py", line 179, in exc_logging_wrapper
    status = run_func(*args)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 427, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 239, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 229, in _get_updated_criteria
    for requirement in self._p.get_dependencies(candidate=candidate):
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\pip\_internal\resolution\resolvelib\provider.py", line 247, in get_dependencies
    return [r for r in candidate.iter_dependencies(with_requires) if r is not None]
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\pip\_internal\resolution\resolvelib\provider.py", line 247, in <listcomp>
    return [r for r in candidate.iter_dependencies(with_requires) if r is not None]
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 401, in iter_dependencies
    for r in self.dist.iter_dependencies():
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\pip\_internal\metadata\pkg_resources.py", line 247, in iter_dependencies
    return self._dist.requires(extras)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2786, in requires
    dm = self._dep_map
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3072, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3082, in _compute_dependencies
    reqs.extend(parse_requirements(req))
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3135, in __init__
    super().__init__(requirement_string)
  File "D:\Comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\pip\_vendor\packaging\requirements.py", line 38, in __init__
    raise InvalidRequirement(str(e)) from e
pip._vendor.packaging.requirements.InvalidRequirement: .* suffix can only be used with `==` or `!=` operators
    numpy (>=1.19.*) ; python_version >= "3.7"
           ~~~~~~~^

**Comment by liaceboy** [comment]
![微信截图_20240701164422](https://github.com/shadowcz007/comfyui-sound-lab/assets/139856834/d5c536eb-88a7-4026-8263-ccf5e39faf01)
